### ISSUE TITLE
Handle URI's containing a comma character

### ISSUE THREAD

**Issue by branislavzelenak** [carlanton/m3u8-parser#28] opened 2020-10-23 07:39 UTC
Hello, in our system we have a common appearance of a live stream HLS master playlist that contains a comma character (for rerouting between streamers/servers) in URIs, like so:

`
#EXTM3U
#EXT-X-VERSION:7
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-STREAM-INF:BANDWIDTH=1496000,FRAME-RATE=25.000,RESOLUTION=856x480
http://5.22.186.164:8080/stream/?fw=true&route=sbb-bg-ku-h1-22,sbb-bg-ne-h1-14&rule=11,null&sp=unitedcloud&asset=masaimedved102srb-hd-p-srpsub&stream=hp1400&conn=UNKNOWN&nf=3&b=3&player=m3u8v&t=36000&adaptive=false&orig=true

#EXT-X-STREAM-INF:BANDWIDTH=446000,FRAME-RATE=25.000,RESOLUTION=512x288
http://5.22.186.164:8080/stream/playlist/hls/?session=e02569a4-5fee-4503-81a2-03ffd859c193&stream=hp350&player=m3u8v

#EXT-X-STREAM-INF:BANDWIDTH=3596000,FRAME-RATE=25.000,RESOLUTION=1920x1080
http://5.22.186.164:8080/stream/playlist/hls/?session=e02569a4-5fee-4503-81a2-03ffd859c193&stream=hp3500&player=m3u8v

#EXT-X-STREAM-INF:BANDWIDTH=7096000,FRAME-RATE=25.000,RESOLUTION=1920x1080
http://5.22.186.164:8080/stream/playlist/hls/?session=e02569a4-5fee-4503-81a2-03ffd859c193&stream=hp7000&player=m3u8v
`

We love using your library, however the URL of the first variant list here is read only until the first ',' character, and thus is incomplete. Would you consider patching so that these kind of URI's are handled properly?

Thanks and keep up the excellent work and contribution!

**Comment by carlanton** [comment] 2020-10-27 19:42
Hi! Thank you for reporting this bug. It was caused by how the parser handled the url internally. It's now fixed and will be released asap :)

**Closed** 2020-10-27 19:41 UTC

**Comment by branislavzelenak** [comment] 2020-10-27 20:58
Hi, that's great, thanks! Please let me know here when you release it on gradle so we can update locally :)

**Comment by branislavzelenak** [comment] 2020-10-27 21:18
I've seen you already released 0.17, it works fine, so thanks again :)
